<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-cache">
<meta value="no-cache, no-store, must-revalidate" name="no-chache">
	
<link href="formatos/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="formatos/estilo_01.css" rel="stylesheet" type="text/css">
<link href="formatos/font/awesome/css/font-awesome.css" rel="stylesheet" type="text/css">