<div class="div_pi text-center">
  <strong>Ubicados: </strong>En el aula....donde más.<br />
  <strong>eMail: </strong>
  <a href="mailto:crodriguezco@est.utn.ac.cr?subject=Solicito información"
    >crodriguezco@est.utn.ac.cr</a
  ><br />
  <strong>Teléfono: </strong>89 47 72 90
</div>
<div class="div_pc">
  Carrera de Tecnologías de la Información<br />
  Curso de Tecnologías y Sistemas Web 2<br />
  Desarrollado completamente a mano con malicia indígena
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
    crossorigin="anonymous"
  ></script>
</div>
