<div class="col-lg-12">
   	<div class="col-lg-6">
      	<img src="imagenes/encabe.png" width="100%" alt="logo">
    </div>
    <div class="col-lg-6"></div>
</div>
<div class="col-lg-12 linea_sep">
	<nav class="navbar navbar-expand-lg bg-light">
		<div class="container-fluid">
            <a class="navbar-brand" href="#">miSitio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#defaultNavbar1" aria-controls="defaultNavbar1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
			<div class="collapse navbar-collapse" id="defaultNavbar1">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="index.php">Inicio</a></li>
					<li class="nav-item"><a class="nav-link" href="tipos.php">Tipos</a></li>
					<li class="nav-item"><a class="nav-link" href="estructuras.php">Estrucutras</a></li>
					<li class="nav-item"><a class="nav-link" href="subrutinas.php">Subrutinas</a></li>
					<li class="nav-item"><a class="nav-link" href="captura.php">Captura 1</a></li>
					<li class="nav-item"><a class="nav-link" href="captura2.php">Captura 2</a></li>
					<li class="nav-item"><a class="nav-link" href="captura3.php">Captura 3</a></li>
					<li class="nav-item"><a class="nav-link" href="combos.php">Combo 1</a></li>
                    <li class="nav-item"><a class="nav-link" href="prueba.php">Prueba</a></li>
				</ul>
			</div>
		</div>
	</nav>
</div>





