<nav class="navbar navbar-dark bg-dark nav_per">
    <div class="container">
        <a class="navbar-brand" href="index.php">
            <img
                src="imagenes/logo.png"
                width="50"
                height="50"
                class="d-inline-block align-top"
                alt=""
            />
        </a>
        <a class="navbar-item nav_per" href="signup.php">
            Registrarse
        </a>
        <a class="navbar-item nav_per" href="login.php">
            Iniciar Sesión
        </a>
        <a class="navbar-item nav_per" href="resenco.php">
            Registrar encomienda
        </a>
        <a class="navbar-item nav_per" href="verenco.php">
            Ver encomienda
        </a>
        <div class="d-flex">
            <a href="https://www.facebook.com/" class="text-muted me-3">
                <i class="fab fa-facebook fa-2x nav_per"></i>
            </a>
            <a href="https://twitter.com/" class="text-muted">
                <i class="fab fa-twitter fa-2x nav_per"></i>
            </a>
        </div>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
            crossorigin="anonymous"
        ></script>
        <style>
          .nav_per {
            color: #FCE4EC;
          }
          .nav_per:hover {
            color: red;
          }
        </style>
    </div>
</nav>
