<div class="col-lg-12">
   	<div class="col-lg-6">
      	<img src="imagenes/encabe.png" width="100%" alt="logo">
    </div>
    <div class="col-lg-6"></div>
</div>
<div class="col-lg-12 linea_sep">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#defaultNavbar1">
                    <span class="sr-only">Botón de navegación</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<a class="navbar-brand" href="#">miSitio</a>
			</div>
			<div class="collapse navbar-collapse" id="defaultNavbar1">
				<ul class="nav navbar-nav">
					<li class="active"><a href="index.php">Inicio</a></li>
					<li><a href="grafica.php">Gráficas</a></li>
					<li><a href="#">Opción 2</a></li>
					<li><a href="#">Opción 3</a></li>
					<li><a href="#">Opción 4</a></li>
				</ul>
			</div>
		</div>	
	</nav>
</div>